### ISSUE TITLE
is there a json file I should use for my meta-snippets or a specific name I should use for my snippet file?

### ISSUE THREAD

**Issue by tylerlindell** [wilsonmontalvo/vsc-meta-snippet#1]
I have the following but it is not working when I go to a `.ts` file and type `js-module`.

```
{
    "@NgModule": {
        "prefix": "js-module",
        "body": [
            "@NgModule({",
                "\timports:      [ $0 ],",
                "\tdeclarations: [ $1 ],",
                "\tbootstrap:    [ $2 ]",
              "})",
              "export class ${3:<condition>} { }"
        ],
        "description": "stub module"
    }
}
```

**Comment by wilsonmontalvo** [comment]
Hi,
The meta-snippet works only inside ".json" files, since this is the usual (if not only) file format where we define snippets.

What you need is to set your "js-module" snippet as User Snipped for TypeScript files. Go to the menu "File > Preferences > User Snippets", and search for TypeScript. This will take you to the "typescript.json" file where you can define all your snippets, there you use Meta-snippet to define them quicker.

Regards.

**Comment by tylerlindell** [comment]
you win! Thank you for your help, Wilson.

I really like using this
